version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3010:3001"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/rpg_nexus"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - rpg_network

  db:
    image: postgres:15
    container_name: rpg_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rpg_nexus
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rpg_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  rpg_network:
    driver: bridge
